version: "3.8"
services:
  nest:
    build: .
    container_name: nest
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - .env:/app/.env

  db:
    image: mariadb:10
    container_name: nest-db
    environment:
      MYSQL_DATABASE: nest
      MYSQL_USER: nest
      MYSQL_PASSWORD: nest
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mariadbdata:/var/lib/mysql

volumes:
  mariadbdata:
